name: DockerHub

# Controls when the workflow will run
on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      -
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        name: Checkout 
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - uses: docker/metadata-action@v4
        id: meta-base
        with:
          images: ${{ secrets.DOCKER_HUB_USERNAME }}/latex
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          flavor: |
            latest=auto
            prefix=
            suffix=-base,onlatest=false
      - uses: docker/build-push-action@v3
        with:
          context: .
          target: base
          push: true
          file: ./Dockerfile
          tags: ${{ steps.meta-base.outputs.tags }}
          labels: ${{ steps.meta-base.outputs.labels }}
      - uses: docker/metadata-action@v4
        id: meta-jp
        with:
          images: ${{ secrets.DOCKER_HUB_USERNAME }}/latex
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          flavor: |
            latest=auto
            prefix=
            suffix=-jp,onlatest=true
      - uses: docker/build-push-action@v3
        with:
          context: .
          target: jp
          push: true
          file: ./Dockerfile
          tags: ${{ steps.meta-jp.outputs.tags }}
          labels: ${{ steps.meta-jp.outputs.labels }}
