name: GitHub Container Registry

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v3
        id: meta-base
        with:
          images: ghcr.io/${{ github.actor }}/latex
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          flavor: |
            latest=auto
            prefix=
            suffix=-base,onlatest=false
      - uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: ./Dockerfile.base
          tags: ${{ steps.meta-base.outputs.tags }}
          labels: ${{ steps.meta-base.outputs.labels }}
      - uses: docker/metadata-action@v3
        id: meta-jp
        with:
          images: ghcr.io/${{ github.actor }}/latex
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          flavor: |
            latest=auto
            prefix=
            suffix=-jp,onlatest=true
      - uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            REGISTRY=ghcr.io
          push: true
          file: ./Dockerfile.jp
          tags: ${{ steps.meta-jp.outputs.tags }}
          labels: ${{ steps.meta-jp.outputs.labels }}
