name: Build and Push to GitHub Containers Registry

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ghcr.io/${{ github.actor }}/latex
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: ./Dockerfile.base
          tags: ${{ steps.meta.outputs.tags }}-base
          labels: ${{ steps.meta.outputs.labels }}
      - uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: ./Dockerfile.jp
          tags: ${{ steps.meta.outputs.tags }}-jp
          labels: ${{ steps.meta.outputs.labels }}
      - uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: ./Dockerfile.vscode
          tags: ${{ steps.meta.outputs.tags }}-vscode
          labels: ${{ steps.meta.outputs.labels }}
      - uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: ./Dockerfile.vscode-jp
          tags: ${{ steps.meta.outputs.tags }}-vscode-jp
          labels: ${{ steps.meta.outputs.labels }}
